config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  get 'events/calendar' => 'events#calendar'
  get 'events/statistics' => 'events#statistics'

  resources :conversations do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end

  resources :events do 
    resources :comments
    resources :participants
  end
  resources :welcome
  resources :searches
  resources :friendships
  resources :requests

  devise_for :admins
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }
  resources :users, :only => [:show]
  resources :users do
    resources :joined_events
  end

  get "mailbox/inbox" => "mailbox#inbox", as: :mailbox_inbox
  get "mailbox/sent" => "mailbox#sent", as: :mailbox_sent
  get "mailbox/trash" => "mailbox#trash", as: :mailbox_trash
  
  root 'welcome#index'
  get '/welcome/show.html.erb', to: 'welcome#show'

end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
	before_action :authenticate_user!

	def new
	end

	def create
		recipients = User.where(id: conversation_params[:recipients])
		conversation = current_user.send_message(recipients, conversation_params[:body], conversation_params[:subject]).conversation
		flash[:success] = "Your message was successfully sent!"
		redirect_to conversation_path(conversation)
	end

	def show
		@receipts = conversation.receipts_for(current_user)
		conversation.mark_as_read(current_user)
	end

	def reply
		current_user.reply_to_conversation(conversation, message_params[:body])
		flash[:notice] = "Your reply message was successfully sent!"
		redirect_to conversation_path(conversation)
	end

	def trash
		conversation.move_to_trash(current_user)
		redirect_to mailbox_inbox_path
	end

	def untrash
		conversation.untrash(current_user)
		redirect_to mailbox_inbox_path
	end


	private

	def conversation_params
		params.require(:conversation).permit(:subject, :body,recipients:[])
	end

	def message_params
		params.require(:message).permit(:body, :subject)
	end
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/views/conversations/_form.html.erb
<%= form_for :conversation, url: :conversations, html: { class: "" } do |f| %>
    <div class="form-group">
      <%= f.label :recipients %>
      <%= f.select(:recipients, User.all.collect {|p| [ p.username, p.id ] }, {}, { multiple: true , class: "form-control" })%>
    </div>
    <div class="form-group">
      <%= f.label :subject %>
      <%= f.text_field :subject, placeholder: "Subject", class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :message %>
      <%= f.text_area :body, class: 'form-control',placeholder: "Type your message here", rows: 4  %>
    </div>

    <%= f.submit "Send Message", class: "btn btn-success" %>

<% end %>

app/views/conversations/_messages.html.erb
<% @receipts.each do |receipt| %>
    <% message = receipt.message %>
    <div class="media">
      <div class="media-left">
        <a href="#">
          <%= image_tag message.sender.avatar.url(:thumb), size: "64x64" %>
        </a>
      </div>
      <div class="media-body">
        <h4 class="media-heading">
          <%= message.sender.username %> <br>
          <small><b>Subject: </b><%= message.subject %></small><br>
          <small><b>Date: </b><%=  message.created_at.strftime("%A, %b %d, %Y at %I:%M%p") %></small>
        </h4>
        <%= message.body %>
      </div>
    </div>
<% end %>

app/views/conversations/new.html.erb
<%= render partial: 'mailbox/folder_view', locals: { is_conversation: true } %>	

app/views/conversations/show.html.erb
<div id='cssmenu' style="background: transparent;z-index: 999;">
  <ul>
    <li><%= link_to 'Home Page', controller: 'welcome' %></li>
    <li><%= link_to 'Compose message', new_conversation_path %></li>
    <li><%= link_to "Events", controller: 'events', action: 'index' %></li>
    <li><%= link_to "Events calendar", controller: 'events', action: 'calendar' %></li>
    <li class='has-sub'><%= link_to "Profile", current_user %>
        <ul>
           <li><%= link_to "View Profile", current_user %></li>
           <li><%= link_to "Messages", controller: 'mailbox', action: 'inbox' %></li>
           <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
           <li><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
        </ul>
    </li>
  </ul>
</div>

<div class="row">
  <div class="col-md-4">
    <div class="panel panel-default">
      <div class="panel-body" style="box-shadow: 10px 10px 10px #000000;">
        <%= render 'mailbox/folders' %>
      </div>
    </div>
  </div>

  <div class="col-md-8">
    <div class="panel panel-default">
      <div style="float: right;">
        <% if conversation.is_trashed?(current_user) %>
            <%= link_to 'Untrash', untrash_conversation_path(conversation), class: 'btn btn-info', method: :post %>
        <% else %>
            <%= link_to 'Move to trash', trash_conversation_path(conversation), class: 'btn btn-danger', method: :post,
                        data: {confirm: 'Are you sure?'} %>
        <% end %>
      </div>
      <div class="panel-body">
        <%= render 'messages' %>
      </div>
      <div class="panel-footer" style="box-shadow: 10px 10px 10px #000000;">
        <!-- Reply Form -->
        <%= form_for :message, url: reply_conversation_path(conversation) do |f| %>
            <div class="form-group" style="box-shadow: 5px 5px 5px #000000;">
              <%= f.text_area :body, placeholder: "Reply Message", rows: 4, class: "form-control" %>
            </div>
            <%= f.submit "Reply", class: 'btn btn-success pull-right' %>
        <% end %>
        <div class="clearfix"></div>
      </div>
    </div>
  </div>

</div>