config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  get 'events/calendar' => 'events#calendar'
  get 'events/statistics' => 'events#statistics'

  resources :conversations do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end

  resources :events do 
    resources :comments
    resources :participants
  end
  resources :welcome
  resources :searches
  resources :friendships
  resources :requests

  devise_for :admins
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }
  resources :users, :only => [:show]
  resources :users do
    resources :joined_events
  end

  get "mailbox/inbox" => "mailbox#inbox", as: :mailbox_inbox
  get "mailbox/sent" => "mailbox#sent", as: :mailbox_sent
  get "mailbox/trash" => "mailbox#trash", as: :mailbox_trash
  
  root 'welcome#index'
  get '/welcome/show.html.erb', to: 'welcome#show'

end

app/controllers/mailbox_controller.rb
class MailboxController < ApplicationController
	before_action :authenticate_user!

	def inbox
		@inbox = current_user.mailbox.inbox
		@active = :inbox
	end

	def sent
		@sent = current_user.mailbox.sentbox
		@active = :sent
	end

	def trash
		@trash = current_user.mailbox.trash
		@active = :trash
	end

end

app/helpers/mailbox_helper.rb
module MailboxHelper
	def unread_messages_count
		# how to get the number of unread messages for the current user
		# using mailboxer
		mailbox.inbox(:unread => true).count(:id, :distinct => true)
	end
end

app/views/mailbox/_folder_view.html.erb
<div id='cssmenu' style="background: transparent;z-index: 999;">
  <ul>
    <li><%= link_to 'Home Page', controller: 'welcome' %></li>
    <li><%= link_to 'Compose message', new_conversation_path %></li>
    <li><%= link_to "Events", controller: 'events', action: 'index' %></li>
    <li><%= link_to "Events calendar", controller: 'events', action: 'calendar' %></li>
    <li class='has-sub'><%= link_to "Profile", current_user %>
        <ul>
           <li><%= link_to "View Profile", current_user %></li>
           <li><%= link_to "Messages", controller: 'mailbox', action: 'inbox' %></li>
           <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
           <li><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
        </ul>
    </li>
  </ul>
</div>

<div class="row" style="z-index: 1;">
  <div class="col-md-4">
    <div class="panel panel-default">
      <div class="panel-body" style="box-shadow: 10px 10px 10px #000000;">
        <%= render 'mailbox/folders' %>
      </div>
    </div>
  </div>

  <div class="col-md-8">
    <div class="panel panel-default">
      <div class="panel-body" style="box-shadow: 10px 10px 10px #000000;">
        <% if is_conversation %>
            <%= render 'conversations/form' %>
        <% else %>
          <% messages.each do |conversation| %>
            <%= link_to conversation_path(conversation) do %>
              <div class='conversation-container'><%= conversation.subject %></div>
            <% end %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>

</div>

app/views/mailbox/_folders.html.erb
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
<ul class="nav nav-pills nav-stacked">
  <li class="<%= active_page(:inbox) %>">
    <%= link_to mailbox_inbox_path do  %>
        <span class="label label-danger pull-right"><%=unread_messages_count%></span>
        <em class="fa fa-inbox fa-lg"></em>
        <span>Inbox</span>
    <% end %>
  </li>
  <li class="<%= active_page(:sent) %>">
    <%= link_to mailbox_sent_path do %>

        <em class="fa fa-paper-plane-o fa-lg"></em>
        <span>Sent</span>
    <% end %>
  </li>

  <li class="<%= active_page(:trash) %>">
    <%= link_to mailbox_trash_path do %>
        <em class="fa fa-trash-o fa-lg"></em>
        <span>Trash</span>
    <% end %>
  </li>
</ul>

app/views/mailbox/inbox.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
  </head>
  <body data-no-turbolinks='true'>
    <%= render partial: 'mailbox/folder_view', locals: { is_conversation: false, messages: @inbox } %>
  </body>
</html>

app/views/mailbox/sent.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
  </head>
  <body data-no-turbolinks='true'>
    <%= render partial: 'mailbox/folder_view', locals: { is_conversation: false, messages: @sent } %>
  </body>
</html>

app/views/mailbox/trash.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
  </head>
  <body data-no-turbolinks='true'>
    <%= render partial: 'mailbox/folder_view', locals: { is_conversation: false, messages: @trash } %>
  </body>
</html>