config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  get 'events/calendar' => 'events#calendar'
  get 'events/statistics' => 'events#statistics'

  resources :conversations do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end

  resources :events do 
    resources :comments
    resources :participants
  end
  resources :welcome
  resources :searches
  resources :friendships
  resources :requests

  devise_for :admins
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }
  resources :users, :only => [:show]
  resources :users do
    resources :joined_events
  end

  get "mailbox/inbox" => "mailbox#inbox", as: :mailbox_inbox
  get "mailbox/sent" => "mailbox#sent", as: :mailbox_sent
  get "mailbox/trash" => "mailbox#trash", as: :mailbox_trash
  
  root 'welcome#index'
  get '/welcome/show.html.erb', to: 'welcome#show'

end

app/models/event.rb
class Event < ActiveRecord::Base
	validates :title, presence: true, length: { minimum: 5, maximum: 20 }	
	validates :sporttype, presence: true
	validates :description, presence: true, length: { minimum: 10, maximum: 500 }
	validates :maxplayers, :numericality => { :greater_than => 1, :less_than_or_equal_to => 30 }
	validates :start_time, presence: true, timeliness: { on_or_after: lambda { Date.current }, type: :date }
	validates :time, presence: true
	validates :location, presence: true, length: { minimum: 5, maximum: 75 }

	has_attached_file :image, styles: { large: "600x600>", medium: "300x300>", thumb: "150x150#" }, :default_url => "/images/missing.png"
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
	has_many :participants, dependent: :destroy
	has_many :comments, dependent: :destroy
	belongs_to :user
	geocoded_by :location
	after_validation :geocode, :if => :location_changed?

	def self.search(search)
	  where("title LIKE ?", "%#{search}%")
	end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /events
  # GET /events.json
  def index
    @events = Event.where('start_time >= ?', Date.current).paginate(:page => params[:page], :per_page => 6).order('id DESC')
    if params[:search]
      @events = Event.search(params[:search]).order("created_at DESC").paginate(:page => params[:page], :per_page => 6).order('id DESC')
    else
      @events = Event.where('start_time >= ?', Date.current).order('created_at DESC').paginate(:page => params[:page], :per_page => 6).order('id DESC')
    end
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @event = Event.find(params[:id])
    @comments = @event.comments
    @comments = @comments.paginate(:page => params[:page], :per_page => 10)
    @hash = Gmaps4rails.build_markers(@event) do |event, marker|
      marker.lat event.latitude
      marker.lng event.longitude
    end
  end

  def calendar
    @events = Event.all
  end

  # GET /events/new
  def new
    @event = current_user.events.build
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = current_user.events.build(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  def notificate_users(event)
    participants = event.participants
    participants_ids = Array.new
    participants.each do |participant|
      participants_ids << participant.user_id
    end
    participants_ids.each do |participant|
      participant_acc = User.find(participant)
      if participant_acc.notifications
        UserMailer.event_change(event, participant_acc).deliver
      end
    end
  end

  def statistics
    @events = Event.all
    @football_events = Event.where("sporttype = ?", "Football")
    @basketball_events = Event.where("sporttype = ?", "Basketball")
    @baseball_events = Event.where("sporttype = ?", "Baseball")
    @volleyball_events = Event.where("sporttype = ?", "Volleyball")
    @handball_events = Event.where("sporttype = ?", "Handball")
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        notificate_users(@event)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:title, :description, :maxplayers, :start_time, :time, :image, :sporttype, :location, :latitude, :longitude)
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_bar_statistics.html.erb
<div id="bar-chart" style="width:100%; height:400px;display: none;">
	<h2>Chart controls</h2>
			<input id='pie-chart-radio-button' type='radio' name='pie-chart' checked>Pie chart</input></br>
			<input id='bar-chart-radio-button' type='radio' name='bar-chart'>Bar chart</input>
</div>
<script type="text/javascript">
	$(function () { 
	    $('#bar-chart').highcharts({
	        chart: {
	            type: 'bar'
	        },
	        title: {
	            text: 'Events statistics'
	        },
	        xAxis: {
	            categories: ['Football', 'Basketball', 'Baseball', 'Volleyball', 'Handball']
	        },
	        yAxis: {
	            title: {
	                text: 'Count'
	            }
	        },
	        series: [{
	            name: 'Sport events',
	            data: [<%= @football_events.count %>, <%= @basketball_events.count %>, <%= @baseball_events.count %>, <%= @volleyball_events.count %>, <%= @handball_events.count %>]
	        }]
	    });
	});
</script>

app/views/events/_form.html.erb
<div class="container">
  <%= form_for @event, html: { multipart: true } do |f| %>
    <% if @event.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

        <ul>
        <% @event.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <div class="form-group">
      <div class="field">
        <%= f.label :title %><br>
        <div class="form-fields">
          <%= f.text_field :title, :required => true, class: "form-control", :placeholder => "Title" %>
        </div>
      </div>
      <div class="field">
        <%= f.label :sporttype %><br>
        <%= f.select :sporttype, ["Football", "Basketball", "Baseball", "Volleyball", "Handball"], :required => true %>
      </div>
      <div class="field">
        <%= f.label :description %><br>
        <div class="form-fields">
          <%= f.text_area :description, :required => true, class: "form-control", :placeholder => "Description" %>
        </div>
      </div>
      <div class="field">
        <%= f.label :maxplayers %><br>
        <div class="form-fields">
          <%= f.number_field :maxplayers, :required => true, class: "form-control" %>
        </div>
      </div>
      <div class="field">
        <%= f.label :start_time %><br>
        <div class="form-fields">
          <%= f.date_field :start_time, :required => true, class: "form-control" %>
        </div>
      </div>
      <div class="field">
        <%= f.label :time %><br>
        <div class="form-fields">
          <%= f.time_field :time, :required => true, class: "form-control" %>
        </div>
      </div>
      <div class="field">
        <%= f.label :location %><br>
        <div class="form-fields">
          <%= f.text_field :location, :required => true, class: "form-control", :placeholder => "Location" %>
        </div>
      </div>
      <div class="field">
        <%= f.label :image %><br>
        <div class="form-fields">
          <%= f.file_field :image, class: "form-control", :style => "margin-bottom: 1%;" %>
        </div>
      </div>
      <div class="actions">
        <%= f.submit "Create", class: "btn btn-primary btn-lg", :style => "margin: 0 auto; display: block; box-shadow: 10px 10px 10px #000000;" %>
      </div>
    </div>
  <% end %>
</div>

app/views/events/_pie_statistics.html.erb
<div id="pie-chart" style="width:100%; height:400px;display: none;"></div>
		<script type="text/javascript">
			$(function () {
			    $('#pie-chart').highcharts({
			        chart: {
			            plotBackgroundColor: null,
			            plotBorderWidth: null,
			            plotShadow: false,
			            type: 'pie'
			        },
			        title: {
			            text: 'Events sport types'
			        },
			        tooltip: {
			            pointFormat: '{series.name}: <b>{point.percentage:.1f}%</b>'
			        },
			        plotOptions: {
			            pie: {
			                allowPointSelect: true,
			                cursor: 'pointer',
			                dataLabels: {
			                    enabled: true,
			                    format: '<b>{point.name}</b>: {point.percentage:.1f} %',
			                    style: {
			                        color: (Highcharts.theme && Highcharts.theme.contrastTextColor) || 'black'
			                    }
			                }
			            }
			        },
			        series: [{
			            name: 'Percentage',
			            colorByPoint: true,
			            data: [{
			                name: 'Football',
			                y: <%= @football_events.count %>
			            }, {
			                name: 'Basketball',
			                y: <%= @basketball_events.count %>
			            }, {
			                name: 'Baseball',
			                y: <%= @baseball_events.count %>
			            }, {
			                name: 'Volleyball',
			                y: <%= @volleyball_events.count %>
			            }, {
			                name: 'Handball',
			                y: <%= @handball_events.count %>
			            }]
			        }]
			    });
			});
		</script>

app/views/events/calendar.html.erb
<!DOCTYPE html>
<html>
	<head>
		<link href='https://fonts.googleapis.com/css?family=Open+Sans:400,300,700&subset=latin,cyrillic' rel='stylesheet' type='text/css'>
		<link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet">
		<link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap-glyphicons.css" rel="stylesheet">
    	<link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
	</head>

	<body data-no-turbolink="true">
		<div id='cssmenu' style="background: transparent;">
	      <ul>
	        <li><%= link_to 'Home Page', controller: 'welcome' %></li>
	        <li><%= link_to 'Events', events_path %>
	        <li><%= link_to 'New Event', new_event_path %></li>
	        <li class='has-sub'><%= link_to "Profile", current_user %>
	            <ul>
	               <li><%= link_to "View Profile", current_user %></li>
								 <li><%= link_to "Messages", controller: 'mailbox', action: 'inbox' %></li>
	               <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
	               <li><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
	            </ul>
	        </li>
	      </ul>
	    </div>

		<div class="header" style="margin-bottom: 1%;">
			<h1 class="header_hero">Events calendar</h1>
		</div>

		<%= month_calendar events: @events do |date, meetings| %>
		  <%= date.day %>

		  <% meetings.each do |meeting| %>
		    <div>
		      <%= link_to meeting.title, meeting %>
		    </div>
		  <% end %>
		<% end %>
	</body>

</html>

app/views/events/edit.html.erb
<!DOCTYPE <!DOCTYPE html>
<html>
	<head>
		<link href='https://fonts.googleapis.com/css?family=Open+Sans:400,300,700&subset=latin,cyrillic' rel='stylesheet' type='text/css'>
	</head>
	
	<body data-no-turbolink="true">	
		<div class="header">
		  <h1 class="header_hero">New Event</h1>
		</div>

		<%= render 'form' %>

		<%= link_to 'Show', @event %> |
		<%= link_to 'Back', events_path %>

	</body>
</html>

app/views/events/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,300,700&subset=latin,cyrillic' rel='stylesheet' type='text/css'>
  </head>
  <body data-no-turbolink="true">
    <div id='cssmenu' style="background: transparent;">
      <ul>
        <li><%= link_to 'Home Page', controller: 'welcome' %></li>
        <li><%= link_to 'New Event', new_event_path %></li>
        <li><%= link_to "Advanced Search", new_search_path %></li>
        <li><%= link_to "Events calendar", controller: 'events', action: 'calendar' %></li>
        <li><%= link_to "Events statistics", controller: 'events', action: 'statistics' %></li>
        <li class='has-sub'><%= link_to "Profile", current_user %>
            <ul>
               <li><%= link_to "View Profile", current_user %></li>
               <li><%= link_to "Messages", controller: 'mailbox', action: 'inbox' %></li>
               <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
               <li><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
            </ul>
        </li>
      </ul>
    </div>
    <p id="notice"><%= notice %></p>

    <div class="header">
      <h1 class="header_hero">Upcoming Events</h1>
    </div>

    <%= form_tag(events_path, :method => "get", id: "search-form") do %>
      <%= text_field_tag :search, params[:search], placeholder: "Search Events", class: "form-control", :style => "width:60%; margin-top: 1%; margin-bottom: 1%; text-align: center; margin-right:auto; margin-left:auto; box-shadow: 10px 10px 10px #000000;" %>
      <%= submit_tag "Search", :name => nil, class: "btn btn-primary", :style => "margin:0 auto; display: block;box-shadow: 10px 10px 10px #000000;" %>
    <% end %>

    <div class="container">
      <div class="row">
          <% @events.each do |event| %>
            <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
                <div class="listing listing-radius listing-success">
                    <div class="listing-content">
                        <h3 class="lead"><%= link_to event.title, event, :style => "text-decoration: none; background-color:transparent; color: #000000;"%></h3>
                        <p><span class="nowrap"><b>Place: </b><%= event.location %></span></p>
                        <p><b>Date: </b><%= event.start_time %></p>
                        <p><b>Time: </b><%= event.time.strftime("%H:%M") %></p>
                        <p><b>Players: </b><%= event.participants.count %>/<%= event.maxplayers %></p>
                    </div>
                </div>
            </div>
          <% end %>
      </div>
      <%= will_paginate @events, renderer: BootstrapPagination::Rails %>
  </div>

  </body>
</html>

app/views/events/new.html.erb
<!DOCTYPE html>
<html>
	<head>
		<link href='https://fonts.googleapis.com/css?family=Open+Sans:400,300,700&subset=latin,cyrillic' rel='stylesheet' type='text/css'>
	</head>
	<body data-no-turbolink="true">
		<div id='cssmenu' style="background: transparent;">
	      <ul>
	        <li><%= link_to 'Home Page', controller: 'welcome' %></li>
	        <li><%= link_to 'Events', events_path %></li>
	        <li class='has-sub'><%= link_to "Profile", current_user %>
	            <ul>
	               <li><%= link_to "View Profile", current_user %></li>
								 <li><%= link_to "Messages", controller: 'mailbox', action: 'inbox' %></li>
	               <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
	               <li><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
	            </ul>
	        </li>
	      </ul>
	    </div>

		<div class="header">
	      <h1 class="header_hero">New Event</h1>
	    </div>

		<%= render 'form' %>

		<%= link_to 'Back', events_path %>

	</body>
</html>

app/views/events/show.html.erb
<!DOCTYPE html>
<html>

  <head> <!-- only if you need custom infoboxes -->

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet">
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap-glyphicons.css" rel="stylesheet">
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBhQFvrIWHNkEFWG8RAIWR73uIh2hYtULg"></script>

    <title><%= @event.title %></title>

    <%= stylesheet_link_tag 'bootstrap.min' %>

  </head>

  <body data-no-turbolink="true">

    <div id='cssmenu' style="background: transparent;">
      <ul>
         <li><%= link_to 'Events', events_path %></li>
         <% if current_user.participate?(@event) %>
           <li class='active has-sub'><a href='#' id="eventLink">Event</a>
            <ul>
              <li>
                <%= render 'participants/participant' %>
              </li>
            </ul>
           </li>
         <% else %>
          <% if current_user == @event.user %>
           <li class='active has_sub'><a href='#' id="eventLink">Event</a>
            <ul>
              <li><%= link_to 'Edit', edit_event_path(@event) %></li>
              <li><%= link_to 'Delete', @event, method: :delete, data: { confirm: 'Are you sure?' } %></li>
            </ul>
           </li>
          <% else %>
            <li><a href='#' id="eventLink">Event</a></li>
          <% end %>
         <% end %>
         <li class='has-sub'><%= link_to "Profile", current_user %>
            <ul>
               <li><%= link_to "View Profile", current_user %></li>
               <li><%= link_to "Messages", controller: 'mailbox', action: 'inbox' %></li>
               <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
               <li><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
            </ul>
         </li>
         <li><a href='#' id="participantsLink">Participants</a></li>
         <li><a href='#' id="nearbyEventsLink">Nearby Events</a></li>
      </ul>
    </div>

    <div class="participants" style="display:none; text-align: center;">
      <h3>Participants</h3>
      <hr>
      <% if @event.participants.size != 0 %>
        <div class="row">
          <% @event.participants.each do |participant| %>
            <div class="profile-header-container">
              <div class="profile-header-img">
                <%= image_tag User.find(participant.user_id).avatar.url(:thumb), class: "img-circle" %>
                <div class="rank-label-container">
                    <span class="label label-default rank-label"><%= link_to User.find(participant.user_id).username, User.find(participant.user_id) %></span>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      <% else %>
        <p>It's lonely here.</p>
      <% end %>
    </div>

    <div class="nearbyEvents" style="display:none; text-align: center;">
      <h3>Nearby Events</h3>
        <div class="row">
          <% if @event.nearbys(20).size != 0 %>
            <% for event in @event.nearbys(20) %>
              <div class="span2">
                <%= image_tag event.image.url, class: 'img-rounded' %>
              </div>
              <div class="span4">
                  <p><%= link_to event.title, event %> (<%= event.distance.round(2) %> miles)</p>
                  <small><cite title="Source Title"><%= event.location %>  <i class="icon-map-marker"></i></cite></small>
                <p>
                  <%= link_to User.find(event.user_id).username, User.find(event.user_id) %> <br>
                  <%= event.participants.count %>/<%= event.maxplayers %> <br>
                  <i class="icon-gift"></i> <%= event.start_time %>
                </p>
              </div>
            <% end %>
          <% else %>
            <p style="text-align:center;">No nearby events</p>
          <% end %>
        </div>
    </div>

    <div class="container-event">

        <div class="row" style="margin: 5%;">

          <h1 style="width: 100%"><%= @event.title %></h1>

          <%= render 'participants/form' %>

          <hr>

          <p>Created by: <%= link_to @event.user.username, @event.user %></p>
          <p><span class="glyphicon glyphicon-time"></span> <%= @event.created_at %></p>
          <%= social_share_button_tag("Join " + @event.title + " -> ", :url => "http://localhost:3000/events/" + @event.id.to_s, :popup => "true") %>

          <hr>

          <%= image_tag @event.image.url(:medium), class: "img-responsive" %>

          <hr>

          <p class="lead"><%= @event.description %></p>
          <p> <b>Type:</b> <%= @event.sporttype %> </p>
          <p> <b>Max players:</b> <%= @event.maxplayers %> </p>
          <p> <b>Date:</b> <%= @event.start_time %> </p>
          <p> <b>Time:</b> <%= @event.time %> </p>
          <p> <b>Location:</b> <%= @event.location %> </p>


            <div id="map" style='width: 100%; height: 200px;'></div>

          <hr>

          <% if @comments != nil %>
            <%= render @comments %>
            <%= will_paginate @comments, renderer: BootstrapPagination::Rails %>
          <% end %>
          <hr>
          <% if user_signed_in? %>
            <%= render 'comments/form' %>
          <% end %>

        </div>
          <hr>

        <p id="notice"><%= notice %></p>

        <script>
            var map = new google.maps.Map(document.getElementById("map"), {
              zoom: 17,
              center: {lat: 0, lng: 0}
            });
            var geocoder = new google.maps.Geocoder();
            geocoder.geocode({"address": "<%= @event.location %>"}, function(results, status) {
              if (status === google.maps.GeocoderStatus.OK) {
                map.setCenter(results[0].geometry.location);
                var marker = new google.maps.Marker({
                  map: map,
                  position: results[0].geometry.location
                });
              } else {
                alert("Geocode error: " + status);
              }
            });
        </script>
    </div>
  </body>
</html>

app/views/events/statistics.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>Statistics</title>
		<script src="http://code.highcharts.com/highcharts.js"></script>
		<script type="http://code.jquery.com/jquery-2.1.4.js"></script>
		<link href='https://fonts.googleapis.com/css?family=Open+Sans:400,300,700&subset=latin,cyrillic' rel='stylesheet' type='text/css'>
	</head>
	<body data-no-turbolink="true">
		<div id='cssmenu' style="background: transparent;z-index: 999;">
	      <ul>
	        <li><%= link_to 'Home Page', controller: 'welcome' %></li>
	        <li><%= link_to 'Events', events_path %>
	        <li><%= link_to "Events calendar", controller: 'events', action: 'calendar' %></li>
	        <li class='has-sub'><%= link_to "Profile", current_user %>
	            <ul>
	               <li><%= link_to "View Profile", current_user %></li>
								 <li><%= link_to "Messages", controller: 'mailbox', action: 'inbox' %></li>
	               <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
	               <li><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
	            </ul>
	        </li>
	      </ul>
	    </div>
		<div class="header" style="margin-bottom: 1%;">
			<h1 class="header_hero">Events statistics</h1>
		</div>
		<div id='chart-controls'>
			<div class="header" style="margin-bottom: 1%;">
				<h2 class="header_hero">Chart controls</h2>
			</div>
			<input id='pie-chart-radio-button' type='radio' name='pie-chart'>Pie chart</input></br>
			<input id='bar-chart-radio-button' type='radio' name='bar-chart'>Bar chart</input>
		</div>
		<%= render 'pie_statistics' %>
		<%= render 'bar_statistics' %>
		<script type="text/javascript">
			$(document).ready(function() {
				$('#pie-chart-radio-button').prop('checked', true);
				$('#pie-chart').show();
				$('#bar-chart-radio-button').click(function() {
					$('#pie-chart').hide();
					$('#pie-chart-radio-button').prop('checked', false);
					$('#bar-chart').show();
				});
				$('#pie-chart-radio-button').click(function() {
					$('#bar-chart').hide();
					$('#bar-chart-radio-button').prop('checked', false);
					$('#pie-chart').show();
				});
			});
		</script>
	</body>
</html>